main/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pharmaplus/', include('pharmaplus.urls')),
    path('', RedirectView.as_view(url='pharmaplus/', permanent = True))
]

main/pharmaplus/urls.py
from django.urls import path
from . import views


app_name = 'pharmaplus'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('about/', views.about, name = 'about'),
    path('register/', views.register, name = 'register'),
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout'),
    path('contact/', views.contact, name = 'contact'),
]

main/pharmaplus/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.

class City(models.Model):
    city = models.CharField(max_length=200)

    def __str__(self):
        return self.city


class Stores(models.Model):

    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100, help_text="name of the store")
    address = models.CharField(max_length=200, help_text="address of the store")
    city = models.ForeignKey( City, on_delete = models.CASCADE, help_text="City")
    phone = models.CharField(max_length=50, help_text="phone number of the store", null=True)

    class Meta:
        ordering = [('city')]

    def __str__(self):
        return self.name

class Medicine(models.Model):

    name = models.CharField(max_length=100, help_text="name of the store")
    price = models.IntegerField()

    def __str__(self):
        return self.name

class Availability(models.Model):

    medicine = models.ForeignKey(Medicine, on_delete=models.CASCADE)
    store = models.ForeignKey(Stores, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return f"{self.medicine.name}, {self.store.name}"




class FeedBack(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.CharField(max_length=1000)


    def __str__(self):
        return f"\nFirst name: {self.first_name}\nEmail: {self.email}\nSubject: {self.subject}"


# class Profile(models.Model):
#     user = models.ForeignKey(User, on_delete = models.CASCADE)
    
#     type_of_customer = [
#         ("C", "Comcumer"),
#         ("P", "Pharmacy")
#     ]

#     customer = models.CharField(
#         max_length = 1,
#         choices=type_of_customer,
#         default="C"
#     )

main/pharmaplus/forms.py
from django import forms
from pharmaplus.models import Stores, Medicine, FeedBack

main/pharmaplus/views.py
from django.shortcuts import render
from pharmaplus.models import FeedBack
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import City, Medicine, Stores, Availability
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import logout as _logout
from django.contrib.auth import login as _login
from django.contrib import messages
# Create your views here.


def index(request):


    if request.method == 'POST':
        medicine = request.POST['s_medicine']
        city = request.POST['s_city']

        stores = Stores.objects.filter(availability__medicine__name=medicine).filter(city__city=city).filter(availability__quantity__gt = 0).distinct()

        context = {
            "stores" : stores
        }

        return render(request, 'result.html', context)

        

    cities = City.objects.all()
    medicines = Medicine.objects.all()

    context = {
        "cities" : cities,
        "medicines" : medicines
    }

    return render(request, 'index.html', context)

def about(request):
    return render(request, 'about.html')

def thankyou(request):
    return render(request, 'thankyou.html')

def login(request):

    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username = username, password = password)

        try:
            _login(request, user)
        except:
            messages.info(request, "Invalid Credentials")
            return HttpResponseRedirect(reverse("pharmaplus:index"))

        return HttpResponseRedirect(reverse("pharmaplus:index"))


    return render(request, 'login.html')

def logout(request):
    _logout(request)
    return render(request, 'index.html')


def contact(request):

    if request.method == 'POST':
        p = FeedBack()
        p.first_name = request.POST['c_fname']
        p.last_name = request.POST['c_lname']
        p.email = request.POST['c_email']
        p.subject = request.POST['c_subject']
        p.message = request.POST['c_message']
        p.save()
        return HttpResponseRedirect(reverse('pharmaplus:index'))

    return render(request, 'contact.html')

def register(request):

    if request.method == "POST":
        first_name = request.POST['c_fname']
        last_name = request.POST['c_lname']
        username = request.POST['c_uname']
        email = request.POST['c_email']
        password = request.POST['c_pass1']
        rePassword = request.POST['c_pass2']
        type_of_customer = request.POST['type_of_user']


        if password != rePassword:
            messages.info(request, "Password does not match")
            return HttpResponseRedirect(reverse("pharmaplus:index"))

        
        try:
            us = User.objects.create_user(username = username, email=email, password=password)
            us.first_name = first_name
            us.last_name = last_name
            us.save()
            return HttpResponseRedirect(reverse("pharmaplus:index"))
        except:
            messages.info(request, "User creation error")
            return HttpResponseRedirect(reverse("pharmaplus:index"))






    return render(request, 'register.html')

main/templates/about.html
{% extends 'base_generic.html' %}
{% load static %}


{% block content %}

  <div class="site-wrap">

    <div class="site-navbar py-2">
      <div class="container">
        <div class="d-flex align-items-center justify-content-between">
          <div class="logo">
            <div class="site-logo">
              <a href="" class="js-logo-clone">PharmaPlus</a>
            </div>
          </div>
          <div class="main-nav d-none d-lg-block">
            <nav class="site-navigation text-right text-md-center" role="navigation">
              <ul class="site-menu js-clone-nav d-none d-lg-block">
                <li ><a href="{% url 'pharmaplus:index' %}">Home</a></li>
                <li class="active"><a href="{% url 'pharmaplus:about' %}">About</a></li>
                <li><a href="{% url 'pharmaplus:contact' %}">Contact Us</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'pharmaplus:logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'pharmaplus:login' %}">Login</a></li>
                <li><a href="{% url 'pharmaplus:register'%}">Register</a></li>
                {% endif %}
              </ul>
            </nav> 
          </div>
        </div>
      </div>
    </div>


    <div class="site-blocks-cover inner-page" style="background-image: url({% static 'images/hero_1.jpg' %});">
      <div class="container">
        <div class="row">
          <div class="col-lg-7 mx-auto align-self-center">
            <div class=" text-center">
              <h1>About Us</h1>
              <p>How many times have you wondered from where to get your medicine? Will it be in stock or your trip to the pharmacy would just go in vain? Which pharmay should you go to ensure the availability and also save your time? We at pharmaplus plan on changin your whole experience of midicine shopping.Just type up what you need and voila!!!</p>ˀ
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="site-section bg-light custom-border-bottom" data-aos="fade">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-6">
            <div class="block-16">
              <figure>
                <img src="{% static 'images/bg_1.jpg' %}" alt="Image placeholder" class="img-fluid rounded">
                <a href="https://vimeo.com/channels/staffpicks/93951774" class="play-button popup-vimeo"><span
                    class="icon-play"></span></a>    
              </figure>
            </div>
          </div>
          <div class="col-md-1"></div>
          <div class="col-md-5">        
            <div class="site-section-heading pt-3 mb-4">
              <h2 class="text-black">Why PharmaPlus?</h2>
            </div>
            <p>
              How many times have you wondered from where to get your medicine? Will it be in stock or your trip to the pharmacy would just go in vain? Which pharmay should you go to ensure the availability and also save your time? We at pharmaplus plan on changin your whole experience of midicine shopping.Just type up what you need and voila!!!
            </p>    
          </div>
        </div>
      </div>
    </div>

        
    

    <div class="site-section bg-light custom-border-bottom" data-aos="fade">
      <div class="container">
        <div class="row justify-content-center mb-5">
          <div class="col-md-7 site-section-heading text-center pt-4">
            <h2>The Team</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 col-lg-6 mb-5">
    
            <div class="block-38 text-center">
              <div class="block-38-img">
                <div class="block-38-header">
                  <img src="{% static 'images/person_4.jpg' %}" alt="Image placeholder" class="mb-4">
                  <h3 class="block-38-heading h4">Aayush Arora</h3>
                  <p class="block-38-subheading">CEO/Co-Founder/Frontend/Backend Desgner</p>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-6 mb-5">
            <div class="block-38 text-center">
              <div class="block-38-img">
                <div class="block-38-header">
                  <img src="{% static 'images/person_2.jpg' %}" alt="Image placeholder" class="mb-4">
                  <h3 class="block-38-heading h4">Anshul Raman</h3>
                  <p class="block-38-subheading">Co-Founder/backend/frontend Developer</p>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-6 mb-5">
            <div class="block-38 text-center">
              <div class="block-38-img">
                <div class="block-38-header">
                  <img src="{% static 'images/person_3.jpg' %}" alt="Image placeholder" class="mb-4">
                  <h3 class="block-38-heading h4">Harsh B parmar</h3>
                  <p class="block-38-subheading">Financial and Technical Advisor</p>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-6 mb-5">
            <div class="block-38 text-center">
              <div class="block-38-img">
                <div class="block-38-header">
                  <img src="{% static 'images/person_1.jpg' %}" alt="Image placeholder" class="mb-4">
                  <h3 class="block-38-heading h4">Himanshu</h3>
                  <p class="block-38-subheading">Intern</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">

            <div class="block-7">
              <h3 class="footer-heading mb-4">About Us</h3>
              <p>We at PharmaPlus tend to bring a revolution in the world of medicine. </p>
            </div>

          </div>

          <div class="col-md-6 col-lg-3">
            <div class="block-5 mb-5">
              <h3 class="footer-heading mb-4">Contact Info</h3>
              <ul class="list-unstyled">
                <li class="address">room no. 39,40 Dr. C V Raman Hostel,IIT-BHU,BHU,varanasi,220015</li>
                <li class="phone"><a href="tel://8077967615">8077967615</a></li>
                <li class="email">aayusharora.cse18@itbhuac.in</li>
              </ul>
            </div>


          </div>
        </div>
      </div>
    </footer>
  </div>

{% endblock %}

main/templates/contact.html
{% extends 'base_generic.html' %}
{% load static %}



{% block content %}

  <div class="site-wrap">


      <div class="site-navbar py-2">
          <div class="container">
            <div class="d-flex align-items-center justify-content-between">
              <div class="logo">
                <div class="site-logo">
                  <a href="" class="js-logo-clone">PharmaPlus</a>
                </div>
              </div>
              <div class="main-nav d-none d-lg-block">
                <nav class="site-navigation text-right text-md-center" role="navigation">
                  <ul class="site-menu js-clone-nav d-none d-lg-block">
                    <li ><a href="{% url 'pharmaplus:index' %}">Home</a></li>
                    <li><a href="{% url 'pharmaplus:about' %}">About</a></li>
                    <li class="active" ><a href="{% url 'pharmaplus:contact' %}">Contact Us</a></li>
                    {% if user.is_authenticated %}
                      <li><a href="{% url 'pharmaplus:logout' %}">Logout</a></li>
                    {% else %}
                      <li><a href="{% url 'pharmaplus:login' %}">Login</a></li>
                      <li><a href="{% url 'pharmaplus:register'%}">Register</a></li>
                    {% endif %}
                  </ul>
                </nav>
              </div>
            </div>
          </div>
        </div>
    

    <div class="bg-light py-3">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mb-0">
            <a href="{% url 'pharmaplus:index' %}">Home</a> <span class="mx-2 mb-0">/</span>
            <strong class="text-black">Contact Us</strong>
          </div>
        </div>
      </div>
    </div>

    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h2 class="h3 mb-5 text-black">Get In Touch</h2>
          </div>
          <div class="col-md-12">
    
            <form action="#" method="post">
              {% csrf_token %}
              
              <div class="p-3 p-lg-5 border">
                <div class="form-group row">
                  <div class="col-md-6">
                    <label for="c_fname" class="text-black">First Name <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" id="c_fname" name="c_fname">
                  </div>
                  <div class="col-md-6">
                    <label for="c_lname" class="text-black">Last Name <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" id="c_lname" name="c_lname">
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-md-12">
                    <label for="c_email" class="text-black">Email <span class="text-danger">*</span></label>
                    <input type="email" class="form-control" id="c_email" name="c_email" placeholder="">
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-md-12">
                    <label for="c_subject" class="text-black">Subject </label>
                    <input type="text" class="form-control" id="c_subject" name="c_subject">
                  </div>
                </div>
    
                <div class="form-group row">
                  <div class="col-md-12">
                    <label for="c_message" class="text-black">Message </label>
                    <textarea name="c_message" id="c_message" cols="30" rows="7" class="form-control"></textarea>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-lg-12">
                    <input type="submit" class="btn btn-primary btn-lg btn-block" value="Send Message">
                  </div>
                </div>
              </div>


            </form>


          </div>
          
        </div>
      </div>
    </div>



    <div class="site-section bg-primary">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <h2 class="text-white mb-4">Offices</h2>
          </div>
          <div class="col-lg-4">
            <div class="p-4 bg-white mb-3 rounded">
              <span class="d-block text-black h6 text-uppercase">Room 40</span>
              <p class="mb-0">Dr. C V Raman, IIT-BHU, BHU, varanasi, UP, 220015</p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="p-4 bg-white mb-3 rounded">
              <span class="d-block text-black h6 text-uppercase">Room 39</span>
              <p class="mb-0">Dr. C V Raman, IIT-BHU, BHU, varanasi, UP, 220015</p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="p-4 bg-white mb-3 rounded">
              <span class="d-block text-black h6 text-uppercase">Room 13</span>
              <p class="mb-0">Dr. C V Raman, IIT-BHU, BHU, varanasi, UP, 220015</p>
            </div>
          </div>
        </div>
      </div>
      
    </div>


    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">

            <div class="block-7">
              <h3 class="footer-heading mb-4">About Us</h3>
              <p>We at PharmaPlus tend to bring a revolution in the world of medicine.</p>
            </div>

          </div>

          <div class="col-md-6 col-lg-3">
            <div class="block-5 mb-5">
              <h3 class="footer-heading mb-4">Contact Info</h3>
              <ul class="list-unstyled">
                <li class="address">Room 39,40, Dr. C V Raman, IIT-BHU, BHU, varanasi, UP, 220015</li>
                <li class="phone"><a href="tel://8077967615">8077967615</a></li>
                <li class="email">aayusharora.cse18@itbhu.ac.in</li>
              </ul>
            </div>


          </div>
        </div>
      </div>
    </footer>
  </div>
{% endblock %}

main/templates/index.html
{% extends 'base_generic.html' %}
{% load static %}

<style>
    #snackbar {
      visibility: hidden;
      min-width: 250px;
      margin-left: -125px;
      background-color: #333;
      color: #fff;
      text-align: center;
      border-radius: 2px;
      padding: 16px;
      position: fixed;
      z-index: 1;
      left: 50%;
      bottom: 30px;
      font-size: 17px;
    }
    
    #snackbar.show {
      visibility: visible;
      -webkit-animation: fadein 0.5s, fadeout 0.5s 2.5s;
      animation: fadein 0.5s, fadeout 0.5s 2.5s;
    }
    
    @-webkit-keyframes fadein {
      from {bottom: 0; opacity: 0;} 
      to {bottom: 30px; opacity: 1;}
    }
    
    @keyframes fadein {
      from {bottom: 0; opacity: 0;}
      to {bottom: 30px; opacity: 1;}
    }
    
    @-webkit-keyframes fadeout {
      from {bottom: 30px; opacity: 1;} 
      to {bottom: 0; opacity: 0;}
    }
    
    @keyframes fadeout {
      from {bottom: 30px; opacity: 1;}
      to {bottom: 0; opacity: 0;}
    }

</style>
<script>
    function myFunction() {
      var x = document.getElementById("snackbar");
      x.className = "show";
      setTimeout(function(){ x.className = x.className.replace("show", ""); }, 3000);


    document.getElementById("demo").innerHTML = window.myFunction();
    } 
</script>
  {% block content %}
  <div class="site-wrap">


    <div class="site-navbar py-2">
      <div class="container">
        <div class="d-flex align-items-center justify-content-between">
          <div class="logo">
            <div class="site-logo">
              <a href="" class="js-logo-clone">PharmaPlus</a>
            </div>
          </div>
          <div class="main-nav d-none d-lg-block">
            <nav class="site-navigation text-right text-md-center" role="navigation">
              <ul class="site-menu js-clone-nav d-none d-lg-block">
                <li class="active"><a href="{% url 'pharmaplus:index' %}">Home</a></li>
                <li><a href="{% url 'pharmaplus:about' %}">About</a></li>
                <li><a href="{% url 'pharmaplus:contact' %}">Contact Us</a></li>
                {% if user.is_authenticated %}
                  <li><a href="{% url 'pharmaplus:logout' %}">Logout</a></li>
                {% else %}
                  <li><a href="{% url 'pharmaplus:login' %}">Login</a></li>
                  <li><a href="{% url 'pharmaplus:register'%}">Register</a></li>
                {% endif %}
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>


    

    <div class="site-blocks-cover" style="background-image: url({% static 'images/hero_1.jpg' %});">
      <div class="container">
        <div class="row">
          <div class="col-lg-7 mx-auto order-lg-2 align-self-center">
            <div class="site-block-cover-content text-center">
              <h2 class="sub-title">Effective and effortless medicines everyday everywhere</h2>
              <h1>Welcome To PharmaPlus</h1>
            </div>


            <div id="demo">
              {% if messages %}
              {% for message in messages %}
              <span class="popuptext" id="myPopup">{{message}}</span>
              {% endfor %}
              {% endif %}
            </div>



            <form action="{% url 'pharmaplus:index' %}" method="POST" >
              {% csrf_token %}
              <div class="input-group mb-3">
                  <div class="input-group-prepend">
                    <label class="input-group-text" for="s_medicine">Medicine</label>
                  </div>
                  <select class="custom-select" id="s_medicine", name="s_medicine">
                    <option selected>Select Medicine</option>
                    {% for medicine in medicines %}
                    <option value="{{medicine.name}}">{{medicine.name}}</option>
                    {% endfor %}
                  </select>
                  <br>
                <div class="input-group-prepend">
                <label class="input-group-text" for="s_city">City</label>
                </div>
                <select class="custom-select" id= "s_city", name="s_city">
                  <option selected>Select City</option>
                  {% for city in cities %}
                  <option value="{{city.city}}">{{city.city}}</option>
                  {% endfor %}
                </select>
                </div>
              


              <div class="site-block-cover-content text-center">
                <div class="form-group row">
                  <div class="col-md-4">
                    <input type="submit" class="btn btn-primary btn-lg btn-block" value="Search Now">
                  </div>
                </div>
              </div>
          </form>   



          </div>
        </div>
      </div>
    </div>

    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">

            <div class="block-7">
              <h3 class="footer-heading mb-4">About Us</h3>
              <p>We at PharmaPlus tend to bring a revolution in the world of medicine.</p>
            </div>

          </div>

          <div class="col-md-6 col-lg-3">
            <div class="block-5 mb-5">
              <h3 class="footer-heading mb-4">Contact Info</h3>
              <ul class="list-unstyled">
                <li class="address">room no. 39,40 Dr. C V Raman Hostel,IIT-BHU,BHU,varanasi,220015</li>
                <li class="phone"><a href="tel://8077967615">8077967615</a></li>
                <li class="email">aayusharora.cse18@itbhu.ac.in</li>
              </ul>
            </div>


          </div>
        </div>
      </div>
    </footer>
  </div>

  {% endblock %}

main/templates/logout.html
{% extends 'base_generic.html' %}
{% load static %}

  {% block content %}
  <div class="site-wrap">


    <div class="site-navbar py-2">
      <div class="container">
        <div class="d-flex align-items-center justify-content-between">
          <div class="logo">
            <div class="site-logo">
              <a href="" class="js-logo-clone">PharmaPlus</a>
            </div>
          </div>
          <div class="main-nav d-none d-lg-block">
            <nav class="site-navigation text-right text-md-center" role="navigation">
              <ul class="site-menu js-clone-nav d-none d-lg-block">
                <li class="active"><a href="{% url 'pharmaplus:index' %}">Home</a></li>
                <li><a href="{% url 'pharmaplus:about' %}">About</a></li>
                <li><a href="{% url 'pharmaplus:contact' %}">Contact Us</a></li>
                <li><a href="{% url 'pharmaplus:login' %}">Login Again</a></li>
                <li><a href="{% url 'pharmaplus:register'%}">Register</a></li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>

    <div class="site-blocks-cover" style="background-image: url({% static 'images/hero_1.jpg' %});">
      <div class="container">
        <div class="row">
          <div class="col-lg-7 mx-auto order-lg-2 align-self-center">
            <div class="site-block-cover-content text-center">
              <h2>You have been logged out</h2>
              <p>
                  login again???
                  <a href="{% url 'login' %}">login</a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">

            <div class="block-7">
              <h3 class="footer-heading mb-4">About Us</h3>
              <p>We at PharmaPlus tend to bring a revolution in the world of medicine.</p>
            </div>

          </div>

          <div class="col-md-6 col-lg-3">
            <div class="block-5 mb-5">
              <h3 class="footer-heading mb-4">Contact Info</h3>
              <ul class="list-unstyled">
                <li class="address">room no. 39,40 Dr. C V Raman Hostel,IIT-BHU,BHU,varanasi,220015</li>
                <li class="phone"><a href="tel://8077967615">8077967615</a></li>
                <li class="email">aayusharora.cse18@itbhu.ac.in</li>
              </ul>
            </div>


          </div>
        </div>
      </div>
    </footer>
  </div>

  {% endblock %}

main/templates/result.html
{% extends 'base_generic.html' %}
{% load static %}

{% block content %}


<div class="site-wrap">


        <div class="site-navbar py-2">
          <div class="container">
            <div class="d-flex align-items-center justify-content-between">
              <div class="logo">
                <div class="site-logo">
                  <a href="" class="js-logo-clone">PharmaPlus</a>
                </div>
              </div>
              <div class="main-nav d-none d-lg-block">
                <nav class="site-navigation text-right text-md-center" role="navigation">
                  <ul class="site-menu js-clone-nav d-none d-lg-block">
                    <li class="active"><a href="{% url 'pharmaplus:index' %}">Home</a></li>
                    <li><a href="{% url 'pharmaplus:about' %}">About</a></li>
                    <li><a href="{% url 'pharmaplus:contact' %}">Contact Us</a></li>
                    {% if user.is_authenticated %}
                      <li><a href="{% url 'pharmaplus:logout' %}">Logout</a></li>
                    {% else %}
                      <li><a href="{% url 'pharmaplus:login' %}">Login</a></li>
                      <li><a href="{% url 'pharmaplus:register'%}">Register</a></li>
                    {% endif %}
                  </ul>
                </nav>
              </div>
            </div>
          </div>
        </div>
    

        

        <!-- <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Address</th>
                <th scope="col">Phone</th>
              </tr>
            </thead>
            <tbody>
              {% for store in stores 
              <tr>
              <th scope="row">{{forloop.counter}}</th>
              <td>{{store.name}}</td>
              <td>{{store.address}}</td>
              <td>{{store.phone}}</td>
            </tr>
              {% endfor 
            </tbody>
        </table> -->

        
        <div class="card-columns">
        {% for store in stores %}
          <div class="card" style="width: 30rem;">
            <img class="card-img-top" src="{% static 'pharmacy.jpeg' %}" alt="pharmacy image cap">
            <div class="card-body">
              <h5 class="card-title">{{store.name}}</h5>
              <p class="card-text">{{store.address}}</p>
            </div>
            <div class="card-body">
              <a href="tel://{{store.phone}}" class="card-link">Contact Us</a>
              <a href="#" class="card-link">Directions</a>
            </div>
          </div>
        {% endfor %}
        </div>

        




    
        <footer class="site-footer">
          <div class="container">
            <div class="row">
              <div class="col-md-6 col-lg-3 mb-4 mb-lg-0">
    
                <div class="block-7">
                  <h3 class="footer-heading mb-4">About Us</h3>
                  <p>We at PharmaPlus tend to bring a revolution in the world of medicine.</p>
                </div>
    
              </div>
    
              <div class="col-md-6 col-lg-3">
                <div class="block-5 mb-5">
                  <h3 class="footer-heading mb-4">Contact Info</h3>
                  <ul class="list-unstyled">
                    <li class="address">room no. 39,40 Dr. C V Raman Hostel,IIT-BHU,BHU,varanasi,220015</li>
                    <li class="phone"><a href="tel://8077967615">8077967615</a></li>
                    <li class="email">aayusharora.cse18@itbhu.ac.in</li>
                  </ul>
                </div>
    
    
              </div>
            </div>
          </div>
        </footer>
      </div>
    

{% endblock %}